package com.arthvault.data.parser.rules

import com.arthvault.data.local.entity.ParserRuleEntity

/**
 * One parser rule as it appears in a signed rule file (T2.2).
 *
 * This is the wire shape, deliberately separate from the Room entity. The two drift
 * for good reasons — the entity carries database concerns like the autogenerated row
 * id, the document carries distribution concerns like [ruleId] — and collapsing them
 * would make a schema migration and a rule-file format change the same event.
 *
 * [ruleId] is the stable identity across versions. Row ids are assigned by SQLite and
 * are meaningless to a rule file; without a stable key an updated rule set could only
 * be applied by deleting every system rule and reinserting, which loses the ability
 * to tell a rule that changed from a rule that was withdrawn.
 */
data class ParserRuleDocumentEntry(
    val ruleId: String,
    val description: String,
    val senderPattern: String,
    val regexPattern: String,
    val amountGroup: Int,
    /** null means "read the direction from the message body" (see SmsParserEngine). */
    val directionGroup: Int?,
    val merchantGroup: Int?,
    val accountGroup: Int?,
    val channelGroup: Int?,
    /** Lower runs first. Ties are broken by [ruleId] so evaluation order is total. */
    val priority: Int,
    val isActive: Boolean
)

/**
 * A complete signed rule file.
 *
 * [signature] is base64 ECDSA-P256-over-SHA-256 of [RuleCanonicalForm.of], *not* of
 * the file bytes. Signing the bytes would mean that reindenting the JSON, or a text
 * editor rewriting its line endings, invalidates a perfectly good rule set — and the
 * predictable response to that is for someone to disable the check.
 */
data class ParserRuleDocument(
    val schemaVersion: Int,
    val rulesVersion: Int,
    val issuedAt: String,
    val signature: String,
    val rules: List<ParserRuleDocumentEntry>
) {
    companion object {
        /** The only schema this build knows how to read. */
        const val SUPPORTED_SCHEMA_VERSION = 1
    }
}

/**
 * Document form to stored form.
 *
 * Shared by [ParserRuleSeeder] and by the tests that exercise the bundled rules, so
 * that what the tests measure is what the app installs. A second mapper written for
 * the tests would be free to be subtly kinder than the real one.
 *
 * @param existingId the row id already holding this [ruleId], so REPLACE updates in
 *   place instead of inserting a duplicate. 0 means "no row yet".
 */
fun ParserRuleDocumentEntry.toEntity(existingId: Long = 0L) = ParserRuleEntity(
    id = existingId,
    ruleId = ruleId,
    ruleName = description.substringBefore('.').take(80),
    senderPattern = senderPattern,
    regexPattern = regexPattern,
    amountGroup = amountGroup,
    directionGroup = directionGroup,
    merchantGroup = merchantGroup,
    accountGroup = accountGroup,
    channelGroup = channelGroup,
    priority = priority,
    isActive = isActive,
    isSystemRule = true
)

/**
 * The order the parser will try these rules in — the same ordering
 * `ParserRuleDao.getActiveRulesList` applies, kept here so the two cannot diverge.
 * `ruleId` breaks ties so the order is total and identical on every device.
 */
fun List<ParserRuleDocumentEntry>.inEvaluationOrder(): List<ParserRuleDocumentEntry> =
    sortedWith(compareBy({ it.priority }, { it.ruleId }))

/** Why a rule file was not accepted. Every case is reported to the user verbatim. */
sealed interface RuleLoadResult {

    data class Loaded(val document: ParserRuleDocument) : RuleLoadResult

    /** The file could not be read or is not the shape a rule file has. */
    data class Malformed(val reason: String) : RuleLoadResult

    /**
     * A schema this build predates. Distinct from [Malformed] because the file may
     * be perfectly valid and simply newer than the app.
     */
    data class UnsupportedSchema(val found: Int, val supported: Int) : RuleLoadResult

    /**
     * The signature did not verify against the bundled public key.
     *
     * The caller keeps whatever rules it already had. Falling back to no rules would
     * turn a tampered or corrupted file into a total ingestion outage, which is a
     * strictly worse outcome than continuing with the last known-good set.
     */
    data object BadSignature : RuleLoadResult
}
